#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

[ -d $SCRIPT_DIR/.venv ] || uv venv --system-site-packages --project $SCRIPT_DIR/src
uv run --project $SCRIPT_DIR/src $SCRIPT_DIR/src/main.py "$@"
