name: Run sbomber
author: Pietro Pasotti
description: Runs the canonical/sbomber tool to perform various SSDLC-related scans using internal services.

inputs:
  manifest:
    description: Absolute path to a sbomber manifest file.
    required: true
  poll-timeout:
    description: Timeout for the poll step, in minutes.
    default: "30"
    required: true

runs:
  using: "composite"
  steps:
  - name: Checkout security scanner
    uses: actions/checkout@v4
    with:
      repository: canonical/sbomber
      path: scanner
  - name: Install uv
    uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb  # v6.1.0
  - name: Install secscan cli
    shell: bash
    run: |
      sudo snap install canonical-secscan-client
      sudo snap connect canonical-secscan-client:home system:home
  - name: Prepare the artifacts
    shell: bash
    run: scanner/sbomber prepare $(realpath ${{ inputs.manifest }})
  - name: Submit the artifacts
    shell: bash
    run: scanner/sbomber submit
  - name: Wait for the scans to finish
    shell: bash
    run: scanner/sbomber poll --wait --timeout ${{ inputs.poll-timeout }}
  - name: Clear the reports dir # in case previous runs left something there already
    shell: bash
    run: rm -rf /tmp/.sbomber-reports/
  - name: Download the reports
    shell: bash
    run: scanner/sbomber download --reports-dir=/tmp/.sbomber-reports/
  - name: Upload reports
    uses: actions/upload-artifact@v4
    with:
      name: ${{ inputs.manifest }}-reports
      path: /tmp/.sbomber-reports/*.json