name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          sudo apt install libapt-pkg-dev
          sudo snap install charmcraft --channel=3.x/candidate --classic
          sudo snap install astral-uv --classic
          python -m pip install tox git+https://salsa.debian.org/apt-team/python-apt.git@2.7.7
          uv python install 3.13
      - name: Run Linter
        run: uv run tox -e lint
      - name: Run Static checks
        run: uv run tox -e static
      - name: Run Unit tests
        run: uv run tox -e unit

      - if: ${{ failure() && runner.debug }}
        name: Setup upterm session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
