name: Test the reusable workflow by running sbomber on this project

on:
    workflow_dispatch:
    pull_request:  # fixme: do not merge this

jobs:
  run-reusable-workflow-test:
    runs-on: [self-hosted]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb  # v0.8.9
      - name: Build wheel
        # this should output a .whl file in ./dist/
        run: uv build --wheel
      - name: Rename wheel
        # This works because we only output one wheel. If that's to ever change, rethink this.
        run: mv ./dist/*.whl ./dist/ci-sbomber-test.whl
      - name: Run sbomber
        uses: canonical/sbomber/.github/actions/run@feat/reusable-workflow
        with:
          manifest: '${{ github.workspace }}/tests/workflow-tests/manifest.yaml'
